### ISSUE TITLE
Trend Charts on Vital signs

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#32]
A graphical representation showing specific vitals at multiple time and day intervals for the following:
Temperature
Blood pressure/pulse
Respiratory rate
Oxygen saturation

**Comment by mandily-p** [comment]
No need to look into the scroll bar issue. This is a browser setting.

**Comment by mandily-p** [comment]
I've updated the still to do list in your comment above @bryan-gilbert I added a new item and removed one.

**Comment by bryan-gilbert** [comment]
More todos:

- [ ] Note that the sort order is based on insertion. 
- [ ] If desired to sort on date and time then need to add form validation and require the day and time fields to be completed.
- [ ] Add a toggle to reverse the sort order. There are two strongly opinionated camps on this topic so why not satisfy them both by a simple toggle?
- [ ] When scrolling oldest leftmost newest rightmost then, on load, have data scrolled all the way to the right to show the newest records and hide the oldest under the left side.
- [ ] Fix the scrolling defect. It sorts one way on load and then the other way on reload.
- [ ] If sorting based on entered day time then add helper text to tell student what the two different date/time inputs mean.  One is the entry time (gee it would be nice if this could be set globally and was automatically inserted for the user and not editable too.) and the other is for the time of measurement.

**Comment by bryan-gilbert** [comment]
We decided to leave sorting until a later date.
For now I've extended the size of the canvas to be large enough to hold lots of records.
Also added sample data.
