### ISSUE TITLE
Grid layout implementation for custom modal forms

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#393]
The medication administration screen and "outside" screens do not use the new grid layout that we've incorporated in the rest of the app. We've closed up the main ticket for the rest of the app and will use this one to track the custom modals.

- [x] MAR
- [x] Edit assignment properties
- [x] Create a new assignment
- [x] Create a new seed
- [x] Edit seed data properties

**Comment by bryan-gilbert** [comment]
PR 466

**Comment by mandily-p** [comment]
Complete
