### ISSUE TITLE
Data Files

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#770]
# Data Files

As a Course Designer user, I want to be able to insert medical reports and images into the EHR to complement the case study because this enables real life like experience

In real EHR systems there are many reports, images, x-rays, cat scans, etc.  To provide a real life experience the EdEHR needs to store and use real life files.  Obtaining these images and sample reports is difficult so it is important to consider reusing these files as much as possible.  The EdEHR can support more than one learning institution so it is important to segment any file storage by institution. 

## Upload - EdEHR System
See #815 
Files can be imported into the EdEHR via a normal file upload experience.  

Consider allowing files to be links to external resources instead of a physical file.  Could then source the actual file from another, publicly available file. 

## Folders

Initially EdEHR will only have one root folder for all files (for any institution).

### File Names and Metadata

File names must be unique within the folder.  If users upload a file with the same name, offer to “replace” or “keep both” or “cancel”.  If the user selects keep both then append a number to the file base name.

Metadata fields:
- licensing and copyright
- tags

### Storage

TBD where to actually store the files. In cloud storage or on the server.  How can different installations of the EdEHR manage this?  On store create thumbnails.

## File Listing

Introduce a new “outside” page listing all files in the system.  Instructors can view this list. Content Editors make changes.  May, in time, add filter by tag.

- Tags
- Image thumbnails.
- Display name and meta data.
- Displays cases (seeds) that refer to the file.
- Display count of all student EHR data sets that refer to the file
- Content Editors can upload new files on this page.
- Content Editors can delete a file that has not been used in any seed or student EHR data.

? renames rules are to be determined.

### Link checking

Will need to be able to scan a EHR data set for file references.
May need to cross reference with system files to find files that are missing.

## “Upload in EHR” and Viewing

Within the EHR any place that would normally allow a EHR user to upload a file we will present a modified upload experience that will only present files available within the user’s institution. 
The action of "upload" in the EHR will create a clickable link that, when clicked, will display the file just as it would work in a real EHR.

- Lab requisitions

### Students can “upload in EHR”

Can anticipate when a simulation application will push new requisitions and reports into the EHR.  Thus, it is necessary that student users can also “upload” within the EHR. 

## Admin access

- Admins can delete any file
- Admins can replace any file by uploading a new file with the same name

## Demonstration mode

TBD what are the implications for the demonstration mode. Each launch creates a new institution. Will likely need to “insert” files virtually rather than physically.  How will this work?

**Comment by bryan-gilbert** [comment]
On the server side
- [] segment file storage by tool consumer id
- [] in base folder provide a json file which a human can use to map the consumer id to institution name
- [] store file with original name
- [] but if name is not unique then append a number
- [] store all files outside the source code in a folder accessible outside the docker images (for backup)
- [] add the directory name into the configuration system
- [] beside each file store a file using the same name plus the extension .json which will hold a JSON object with metadata about the file
- [] metadata to include properties collected in the UI, for example, file source, copyright status, etc.
- [] thumbnails?
- [] provide API to get a file
- [] provide API to get list of files, ready to enhance with support for page X of Y and filtering and sorting

On the client side
- [] Create a drag-n-drop area for users to drop a file
- [] look into limits and disable DnD when limit is reach
- [] put the file upload into a dialog with a form
- [] on the form add in metadata fields (see above)
- [] look into how the vue upload component might support thumbnails
- [] list files
- [] list items show link to view file, thumbnail if present (separate API call), and metadata
- [] listing needs to be ready for paging the list
- [] listing needs to be ready for filtering and sorting
