### ISSUE TITLE
Add tests for page data definitions

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#792]
# Add unit tests for page data definition
To support issue #745 
we will add tests to the page data definitions
because we need to know if the definitions are following the rules

## Details

- [x]  Test that every element key is unique throughout all pages.
- [x] Test that no element has a inputType that is not expected.
- [x] Test that every dependentOn clause refers to an element or to elements that exist.  Plus, look at the use of EHR Type
- [x] Test that every element of type assetLink has values in assetBase and assetName (maybe assetBase is optional?)
- [x] Test that every element of type select has a list of values in Options and that this list has length > 1
- [x] Test that any elements with a value in passToFunction refers to another element that exists. These elements should also have a list of Options (length > 1) with the format N=label. 
- [x] Test that any element with a validator refers to one of the supported validations.
