### ISSUE TITLE
Unit testing MAR and medications

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#806]
## MAR and Medications
The EHR pages related to medications and medication administration records lacks unit tests. This is a complex part of the application and needs coverage as soon as possible.

## Do not test scheduling algorithms
The EdEHR will soon get  the feature of 'day' and 'time' as these will come from the new concept of a signin page.  Thus, all the complexity in the mar system with computing which MAR buttons to show will be rewritten.  Let's not write tests for code that will be removed. The focus, for now, is all the infrastructure needed to support the MAR page, excluding the scheduling algorithms (e.g. do not test methods like mar-today.js getTodaysSchedule(..)

## Tasks
- [x] mar-entity.js (validation, asObjectForAPI, constructor,...)
- [x] med-order.js (test the various ways this object can be constructed and in each case the getters)
- [x] mar-today (break this out into its own issue cause it's complex)
- [x] mar-summary (break this out into its own issue cause it's complex)
 

## Related issues
#807 for mar-helper
