### ISSUE TITLE
Unit test mar-helper

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#807]
## Task
To support EPIC #806 
we will build unit tests for mar-helper.js

## Details
- [x]  create a set of test data seeds with suitable sample medication records and 
   - no mar records
   - some mar records for the first day
- [x]  unit test the constructor of the mar helper with these seeds
- [x]  test the getters such as getEhrData_MarRecords, getMarTableKey, etc.
