### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#815]
## File Upload 
Parent #770 

Focus on the server side. Minimal client side to support development.

## Description
Provide the File Upload functionality

On the server side
- [x] segment file storage by tool consumer id
- [x] make sure file names are safe for unix and windos
- [x] in base folder provide a json file which a human can use to map the consumer id to institution name
- [x] store file with original name
- [pass] if name is not unique then let it overwrite for now. Later could append a number
- [x] store all files outside the source code in a folder accessible outside the docker images (for backup)
- [x] add the directory name into the configuration system

On the client only build prototype code to support the development of the above
- [x] new 'EhrFiles' page
- [x] select files
- [x] upload file(s)

**Comment by bryan-gilbert** [comment]
On the server side
- [] segment file storage by tool consumer id
- [] in base folder provide a json file which a human can use to map the consumer id to institution name
- [] store file with original name
- [] but if name is not unique then append a number
- [] store all files outside the source code in a folder accessible outside the docker images (for backup)
- [] add the directory name into the configuration system
- [] beside each file store a file using the same name plus the extension .json which will hold a JSON object with metadata about the file
- [] metadata to include properties collected in the UI, for example, file source, copyright status, etc.
- [] thumbnails?
- [] provide API to get a file
- [] provide API to get list of files, ready to enhance with support for page X of Y and filtering and sorting

On the client side
- [] Create a drag-n-drop area for users to drop a file
- [] look into limits and disable DnD when limit is reach
- [] put the file upload into a dialog with a form
- [] on the form add in metadata fields (see above)
- [] look into how the vue upload component might support thumbnails
- [] list files
- [] list items show link to view file, thumbnail if present (separate API call), and metadata
- [] listing needs to be ready for paging the list
- [] listing needs to be ready for filtering and sorting
