### ISSUE TITLE
Test driven repair - page defs

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#817]
**Describe the bug**
See https://github.com/BCcampus/edehr/pull/816
The new unit tests are failing. This indicates some development is needed to repair the code.

- [ ]  Test that every element of type assetLink has values in assetBase and assetName (maybe assetBase is optional?)
- [ ]  Test that every element of type select has a list of values in Options and that this list has length > 1
- [ ]  Test that any element with a validator refers to one of the supported validations.
