### ISSUE TITLE
iPhone basic responsiveness

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#826]
**Describe the bug**
Although the application is not meant to be fully usable on a mobile device (iPhone) it should work at a basic level. Currently most dialogs are unworkable on iPhone

**Expected behavior**

- [x] Demo log in dialog 
- [x] EHR page dialogs
- [x] assess other dialogs and list here any that need work.
- [x] fix others.
