### ISSUE TITLE
Save images on server with appropriate metadata - especially copyright

### ISSUE THREAD

**Issue by bryan-gilbert** [BCcampus/edehr#842]
The plan is to save smaller thumbnail versions of files to provide quick response times when listing files with thumbnail image.
The resized image needs to copy some of the metadata fields.

Ignore the EXIF metadata because it may be bloated with a camera thumbnail image and it is mainly concerned with camera information. But also because it can contain personally identifiable information such as GPS coordinates.

Keep the IPTC IIM and XMP blocks.  These blocks are where copyright information is stored too. (Yes the EXIF might have this but not when the owner is serious about their copyright because they'd be sure to apply it in the standard location.)

Good article on applying Creative Commons license to photos.
https://www.carlseibert.com/creative-commons-needs-metadata/?highlight=Rights%20Usage

- [x] Provide an API that receives an image and responds with the copyright and caption information.  Can use this prior to save to let the user be aware of copyright on the images.
- [x] Let the download action happen after displaying the above.
- [ ] On save to server transform the file into a webp version because this is the most compact and fastest form. 
- [ ] Save a thumbnail
- [ ] Provide URL to view thumbnail
- [ ] can view full (webp) image via url

**Comment by bryan-gilbert** [comment]
Close issue. See https://github.com/BCcampus/edehr/issues/863 for thumbnails
