### ISSUE TITLE
Student view - Remove button to add data on some pages

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#87]
Some pages will never have students add or edit data on them. These are reference pages that GIVE them information to make health decisions.

Students do not need to see create buttons.

Admins do need the create functionality on each page so that they are able to create new assignments and seed data.

Note from Bryan: Do this at the table/form level rather than the page

These pages should have the button hidden when students are using the app:
- [ ] Demographics
- [ ] Allergies
- [ ] History: medical
- [ ] History: psychosocial
- [ ] History: surgical
- [ ] History: immunization
- [ ] History: Family history
- [ ] Past appointments
- [ ] MAR
- [ ] Discharge summary
- [ ] Billing
- [ ] Consults
- [ ] Lab reports
- [ ] Medical imaging
- [ ] Operative reports and anaesthesia record
- [ ] Standardized assessment tools
- [ ] Code lookup

**Comment by bryan-gilbert** [comment]
Consider this for MVP.
