### ISSUE TITLE
Update MAR

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#90]
After sitting down and hashing out how the MAR works, we came up with a pretty good combination of Cerner and Meditech. As the Invision wireframes are no longer being updated, I've included the new wireframes here.

As a first step, the medication orders modal will have a multi-select box with various times of the day to choose from.

**Details** 
- PRN (as needed) go after the scheduled meds
- If a piece of data does not exist (ie reason) don't display anything in it's place
- Styling doesn't need to look like the screenshots, whatever cascades down from the other css is fine.

![setup - current visit mar today](https://user-images.githubusercontent.com/20425828/53379673-643d0200-391f-11e9-8712-1334d9ce3243.png)
![setup - current visit mar - history](https://user-images.githubusercontent.com/20425828/53379675-643d0200-391f-11e9-92dd-0af9b61c901b.png)

**Comment by mandily-p** [comment]
@bryan-gilbert Can you please move the `day #` to the `Today` tab label? So it would look like `Today - Day 2`

**Comment by mandily-p** [comment]
I also see double row labels. Can you get rid of the small text one?


![Uploading Screen Shot 2019-04-01 at 8.18.06 PM.png…]()

**Comment by mandily-p** [comment]
@bryan-gilbert I'm making a to do list for you to finish this ticket up.
## Both tabs
- [ ] Remove the title under each tab (`Medication Administration Records` and `Medication summary`)

## Today
- [ ] Add the day number to the `today` tab title. For example `Today - Day 3`
- [ ] Label the time column `Time`
- [ ] Label the medication column `Medication order`
- [ ] Remove larger time labels
- [ ] From the third column, remove `Scheduled for` and `medications`
- [ ] Top align text in columns

## Summary
- [ ] Add a `Status` column before the medication in each row
- [ ] Each medication needs to be displayed with it's dose, route, reason and notes in the first column
- [ ] The header of each column should be the scheduled day and time
- [ ] In each cross cell for a medication and a scheduled day and time, should be the actual time and the person who administered the medication
- [ ] Remove each word before the colon, for example, instead of `When: Day 0 - 03:00` is should say `Day 0 - 03:00`
- [ ] Replace the dash between the `day` and `number` with a space. 
- [ ] Add a vertical line between each day (not each time)

**Comment by bryan-gilbert** [comment]
Did as many of the tasks and I can.  Not sure about the Time column and we need a status field in the record before we can display any property like this.

**Comment by mandily-p** [comment]
@bryan-gilbert I've went in and made some changes to this. I've done what I can, and am sending the to do list (I added some new items) back to you.

**Comment by bryan-gilbert** [comment]
We discussed the status field and will not implement anything related to that for this open issue. It'll be a topic for the future. Mainly, because we have no way to edit a table row, at this time, so there is little reason to add a flag that can't be changed to reflect workflow.
